AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  HCWSSViewer:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: YOUR_FUNCTION_ROLE
      Environment:
        Variables:
          DYNAMO_TABLE_NAME: YOUR_TABLE_NAME
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
