AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  HCWSSViewer:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: YOUR_FUNCTION_ROLE
      Environment:
        Variables:
          DYNAMO_TABLE_NAME: YOUR_TABLE_NAME
          DYNAMO_ENDPOINT: YOUR_DYNAMO_ENDPOINT
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: GET
